### ISSUE TITLE
Failing builds and PHP 8 support

### ISSUE THREAD

**Issue by hibariya** [stripe-samples/sample-ci#8]
# Bug report

## Describe the bug

It looks like some PHP samples don't support PHP 8. Since the latest composer Docker image bundles PHP 8.0.2,  composer failed to satisfy the dependencies in [this build](https://github.com/stripe-samples/accept-a-card-payment/runs/1972142343) in accept-a-card-payment. Considering the cause, I think the other repositories may also have the same issue.

This is the detailed error messages:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vlucas/phpdotenv v3.4.0 -> satisfiable by vlucas/phpdotenv[v3.4.0].
    - vlucas/phpdotenv v3.4.0 requires php ^5.4 || ^7.0 -> your PHP version (8.0.2) does not satisfy that requirement.
```

## To Reproduce

https://github.com/stripe-samples/accept-a-card-payment/runs/1972142343

## Expected behavior

The build passes.

## Additional context

As for accept-a-card-payment, this PR (https://github.com/stripe-samples/accept-a-card-payment/pull/58) will fix the issue for `without-webhooks`. However, we will need similar changes on `using-webhooks`, too.

Also, we could make CI use PHP 7 for now.

**Comment by hibariya** [comment]
I noticed that after removing the `composer.lock`, `composer install` completes without errors. Also, I couldn't see this error when running tests on checkout-one-time-payments which does not have `composer.lock` in the repository. Maybe we could just remove or update the lock files in accept-a-card-payment?

Here's the steps I did to reproduce the error on my local machine:
```
(in stripe-samples/accept-a-card-payment)
$ cd decline-on-card-authentication/server/php-slim/
$ md5sum composer.lock 
f86a60eade59b11c36205b830e7fb151  composer.lock
$ docker run --rm -it --workdir=/work -v $PWD:/work composer:1.10 /bin/bash
bash-5.1# composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vlucas/phpdotenv v3.4.0 -> satisfiable by vlucas/phpdotenv[v3.4.0].
    - vlucas/phpdotenv v3.4.0 requires php ^5.4 || ^7.0 -> your PHP version (8.0.2) does not satisfy that requirement.
```

After removing `composer.lock`, the installation completed successfully:
```
bash-5.1# rm composer.lock 
bash-5.1# composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
bash-5.1# 
exit
$ md5sum composer.lock
e8e154af97d620a731d6aad724bc9029  composer.lock
```

**Comment by cjavilla-stripe** [comment]
yeah feel free to remove composer.lock. That seems peaceful

**Comment by hibariya** [comment]
Thanks. I created a PR that removes the lock files: https://github.com/stripe-samples/accept-a-card-payment/pull/69
